In [1]:
for i in Rent.objects.all():
    if i.stop:
        cost=(i.stop-i.start).seconds//3600*i.room.hour_price
        i.cost = cost
        try:
            i.save()
        except:
            print(i.cost)

In [5]:
from django.db.models import Sum
qs=Member.objects.all().annotate(total_cost=Sum('rent__cost'))
for i in qs:
    print(i.id,i.total_cost)

1 9238.00
2 8545.00
3 10453.00
4 11406.00
5 8423.00
6 10429.00
7 10210.00
8 13043.00
9 12089.00
10 13266.00
11 11880.00
12 7807.00
13 8611.00
14 10035.00
15 10747.00
16 9695.00
17 9873.00
18 7804.00
19 8905.00
20 5823.00
21 9048.00
22 8465.00
23 10748.00
24 11983.00
25 8781.00
26 5797.00
27 9403.00
28 9681.00
29 8764.00
30 11038.00
31 6071.00
32 7557.00
33 6537.00
34 6838.00
35 8663.00
36 12935.00
37 9021.00
38 8724.00
39 9298.00
40 10154.00
41 9683.00
42 7340.00
43 10738.00
44 8480.00
45 12506.00
46 9335.00
47 7437.00
48 9450.00
49 11320.00
50 9697.00
51 10697.00
52 7323.00
53 8014.00
54 7629.00
55 10996.00
56 10279.00
57 10087.00
58 7405.00
59 14730.00
60 8863.00
61 11405.00
62 9204.00
63 11645.00
64 10012.00
65 11176.00
66 12651.00
67 8169.00
68 13910.00
69 10809.00
70 7578.00
71 7143.00
72 7486.00
73 7776.00
74 11583.00
75 9423.00
76 12047.00
77 13668.00
78 9260.00
79 9695.00
80 10829.00
81 12963.00
82 13593.00
83 7217.00
84 5470.00
85 10689.00
86 9747.00
87 11187.00
88 7155.00
89 14303.00
90 9284.00
91 7376.00
92 8525.00
93 12945.00
94 15116.00
95 9053.00
96 8616.00
97 7724.00
98 8527.00
99 10489.00
100 9295.00